### ISSUE TITLE
Survey Invitation Log

### ISSUE THREAD

**Issue by ThomasVermes** [lsgs/redcap-record-logging-link#1]
Dear Luke,

I was wondering if you could add another link pointing the "Survey Invitation Log"? 

'+app_path_webroot+'Surveys/invite_participants.php?pid=<?=$project_id?>&email_log=1&pagenum=1&filterBeginTime=&filterEndTime=&filterInviteType=&filterResponseType=&filterSurveyEvent=0-0&filterRecord=<?=$record?>

that would also be really helpfull,

many thanks
Thomas

**Comment by lsgs** [comment]
@ThomasVermes: v1.2.0 now includes links to the Survey Invitation Log and to the Notification Log for those project users with the  appropriate permissions.
